MAX_KEY_LEN = 500

GUID_START_BLOCK_LEN = 8
GUID_REMAINING_LEN = 28
GUID_DASH_POSITIONS = [8, 13, 18, 23]
GUID_POSSIBLE_CHARS = "0123456789abcdef-"
GUID_SUCCESS_OFFSET = 2
GUID_REPLACEMENT = "<GUID>"

AUTH0_ID_MAX_LEN = 48
AUTH0_ID_POSSIBLE_CHARS = "0123456789abcdef"
AUTH0_ID_REPLACEMENT = "<AUTH0_ID>"
AUTH0_HEAD = "auth0"
AUTH0_VERTICAL_BAR_CODE = "%7C"

PANELS_MEATBALL_MENU_TESTID_TEMPLATE = "data-testid Panel menu "
PANEL_CARD_TESTID_TEMPLATE = "data-testid Panel header "
EXPLORE_DATA_TESTID = "data-testid Panel menu item Explore"
RADIO_BUTTONS_DATA_TESTID = "data-testid radio-button"
DOWNLOAD_ARIA_LABEL = "Download"
TIME_RANGE_OPEN_TESTID = "data-testid TimePicker Open Button"
TIME_RANGE_FROM_FIELD_TESTID = "data-testid Time Range from field"
REFRESH_DATA_TESTID = "data-testid RefreshPicker run button"